// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqhvzhlzvpjinmkhigsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxaHZ6aGx6dnBqaW5ta2hpZ3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzA2MTksImV4cCI6MjA2MjcwNjYxOX0.XeG1HO7ROqPQM1vGUGcKSncg7WckU4f3mu6yvzQq4GM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);